apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  containers:
  - name: db
    args:
    - --transaction-isolation=READ-COMMITTED
    - --binlog-format=ROW
    command:
    - docker-entrypoint.sh
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_DATABASE
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_PASSWORD
    image: docker.io/library/mariadb:10.5
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: home-pi-deployments-nextcloud-data-db
  - name: app
    env:
#    - name: REDIS_HOST_PASSWORD
#      value: +HZsGCIxzmWXtwoogEkheB2PlJDXCOWHDWqwMlS76ueOAERbo11RPQ==
    - name: MYSQL_HOST
      value: 127.0.0.1
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_DATABASE
    - name: REDIS_HOST
      value: 127.0.0.1
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: nextcloud-config
          key: MYSQL_PASSWORD
    image: registry.hub.docker.com/library/nextcloud:stable
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /var/www/html
      name: home-pi-deployments-nextcloud-data-html
    workingDir: /var/www/html
  - name: cache
    command:
    - redis-server
#    - --requirepass
#    - okCH6R/qtzvn+f/gnvuadt++/9CDGx1n+mYCfRIBPk9WvN31/QK3Yg==
    image: docker.io/library/redis:alpine
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /var/tmp
      name: tmpfs
    - mountPath: /run
      name: tmpfs
    workingDir: /data
  - name: cron
    image: registry.hub.docker.com/library/nextcloud:stable
    command: ["/cron.sh"]
    volumeMounts:
    - mountPath: /var/www/html
      name: home-pi-deployments-nextcloud-data-html
    workingDir: /var/www/html
  volumes:
  - hostPath:
      path: /home/pi/data/nextcloud/data/db
      type: Directory
    name: home-pi-deployments-nextcloud-data-db
  - hostPath:
      path: /home/pi/data/nextcloud/data/html
      type: Directory
    name: home-pi-deployments-nextcloud-data-html
  - hostPath:
      path: /dev/shm/nextcloud-tmpfs
      type: DirectoryOrCreate
    name: tmpfs
