apiVersion: v1
kind: Pod
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  containers:
  - name: service
    image: registry.hub.docker.com/library/caddy:2
    volumeMounts:
    - mountPath: /data/
      name: data-caddy-data
    - mountPath: /etc/caddy/Caddyfile
      name: home-pi-deployments-caddy-caddyfile
      readOnly: true
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    - containerPort: 2019
      hostPort: 2019
      protocol: TCP
  volumes:
  - hostPath:
      path: /home/pi/deployments/proxy/Caddyfile
      type: File
    name: home-pi-deployments-caddy-caddyfile
  - hostPath:
      path: /home/pi/data/caddy_data
      type: Directory
    name: data-caddy-data
